Dev
WildCodeSchool/2023-02-JS-FT-Lyon-P3-InnoVin pull request #13
Opened 2023-07-05 08:15 UTC by Wraethh

2023-07-06 14:27 UTC, PPaillard requested changes
vos services coté front, c'est au top ça :-)

2023-07-06 14:27 UTC, PPaillard commented on backend/database.sql
>  VALUES (0, 0, 0, "Yann", "Richard", "1989-07-12", "yann.richard9@gmail.com", "$argon2id$v=19$m=16,t=2,p=1$cXFnN2s1ZHU0aTAwMDAwMA$XFP3Vrp4/huxiy9p4p2EAw", "Rue de l'exemple", 69000, "Lyon", "User");
Toujours pas  bon cette valeur de 0 pour des ids.

2023-07-06 14:27 UTC, PPaillard commented on backend/database.sql
Les index servent a rien dans ce contexte
Pas de delete / update action non plus, ça alourdis pour rien

2023-07-06 14:27 UTC, PPaillard commented on backend/src/controllers/userControllers.js
> +      res.location(`/register/${result.insertId}`).sendStatus(201);
sur la route /register/${result.insertId}, on peut vraiment récupérer l'utilisateur qu'on vient d'enregistrer?
ça sert a quoi?

2023-07-06 14:27 UTC, PPaillard commented on backend/src/router.js
Attention aux routes qui nécessite une auth si besoin ;-)
C'est pas à corriger, mais mettez ça de coté, faudra pas l'oublier

2023-07-13 08:31 UTC, MargauxDF requested changes

2023-07-13 08:31 UTC, MargauxDF commented on backend/src/models/SessionHasWineManager.js
> +  }
Pourquoi réécrire celles ci de méthodes ???

2023-07-13 08:31 UTC, MargauxDF commented on frontend/src/pages/Tasting.jsx
> +            } /* sx={{ display: "flex", justifyContent: "center" }} */
commentaire a supprimer si pas utilisé

2023-07-13 09:34 UTC, MargauxDF approved these changes

2023-07-18 16:04 UTC, PPaillard approved these changes
Super la correction BDD

2023-07-18 16:04 UTC, PPaillard commented on backend/src/router.js
Je bloque pas, mais faut m'expliquer que je comprenne

2023-07-18 16:06 UTC, merged